name: 'State Drift Report'
description: 'Generate a Terraform state drift report in Markdown'
inputs:
  run-id:
    required: false

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
